# Generated by Django 5.0 on 2024-04-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
