# Generated by Django 5.0 on 2024-03-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='product_categories',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptop and Desktop', 'Laptop and Desktop'), ('Storage', 'Storage'), ('Camera and Accessories', 'Camera and Accessories'), ('Gaming', 'Gaming'), ('Smart Wearables', 'Smart Wearables'), ('Television', 'Television')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
