# Generated by Django 5.0 on 2024-04-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptop and Desktop', 'Laptop and Desktop'), ('Storage', 'Storage'), ('Camera and Accessories', 'Camera and Accessories'), ('Gaming', 'Gaming'), ('Smart Wearables', 'Smart Wearables'), ('Television', 'Television'), ('Heaters', 'Heaters'), ('Steamer', 'Steamer'), ('Humidifiers', 'Humidifiers'), ('Kettles', 'Kettles')], max_length=50),
        ),
    ]
