# Generated by Django 5.0 on 2024-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptop and Desktop', 'Laptop and Desktop'), ('Storage', 'Storage'), ('Camera and Accessories', 'Camera and Accessories'), ('Gaming', 'Gaming'), ('Smart Wearables', 'Smart Wearables'), ('Television', 'Television'), ('Heaters', 'Heaters'), ('Steamer', 'Steamer'), ('Humidifiers', 'Humidifiers'), ('Kettles', 'Kettles'), ('Air Conditioners', 'Air Conditioners'), ('Air Coolers', 'Air Coolers'), ('MINI FRIDGE', 'MINI FRIDGE'), ('Hand Held Fans', 'Hand Held Fans'), ('De Humidifiers', 'De Humidifiers'), ('Fans', 'Fans'), ('Air Purifiers', 'Air Purifiers'), ('Portable fans', 'Portable fans')], max_length=50),
        ),
    ]
